spring:
    profiles:
        active: 
        
---
spring:
    profiles:
        active: dev #开发环境
        application:
          name: microservicecloud-config-dev
---
spring:
    profiles:
        active: test #开发环境
        application:
          name: microservicecloud-config-test1
